[build-system]
requires = [
    "setuptools>=68",
]
build-backend = "setuptools.build_meta"

[project]
name = "PSU-Control---MQTT"
version = "1.1.0"
description = "Control external MQTT switch with PSU Control"
authors = [
    { name = "oerkel47" },
]
requires-python = ">=3, <4"
dependencies = []
dynamic = [
    "license",
]

[project.entry-points."octoprint.plugin"]
psucontrol_mqtt = "octoprint_psucontrol_mqtt"

[project.urls]
Homepage = "https://github.com/oerkel47/OctoPrint-PSUControl-MQTT"

[project.optional-dependencies]
develop = [
    "go-task-bin",
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = [
    "octoprint_psucontrol_mqtt",
    "octoprint_psucontrol_mqtt.*",
]
